version: "3.9"
services:
  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_DB=crowd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./Backend
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=crowd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./Frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
